adopt/urls.py
from django.urls import path
from .views import *

app_name="adopt"

urlpatterns = [
    path('',adopt_main,name="adopt_main"),
    path('adopt_try/<int:id>', adopt_try,name="adopt_try"),
    path('adopting/<int:id>',adopting,name="adopting"),
] 

bbubbu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name="index"),
    path('main/',main, name='main'),
    # path('accounts/',include("allauth.urls")),
    path('stories/',include('stories.urls')),
    path('user/',include('user.urls')),
    path('matching/',include('matching.urls')),
    path('adopt/',include('adopt.urls')),
    path('conversation/',include('conversation.urls')),
    path('dormline/',include('dormline.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dormline/urls.py
from django.urls import path
from .views import *

app_name='dormline'
urlpatterns = [
    path('view_random/<str:id>', view_random, name='view_random'),
    path('follow/<str:id>',follow, name='follow'),
] 

matching/urls.py
from django.urls import path
from .views import *

app_name="matching"

urlpatterns = [
    path("match_upline/<int:id>",match_view, name="match_view" ),
    # path("school_line/<int:id>",shcool_line, name="school_line" ),

] 

user/urls.py
from django.urls import path
from .views import *

app_name="user"
urlpatterns = [
    path('login',login_view, name='login'),
    path('signup/',signup_view,name='signup'),
    path("main/", main, name='main'),
    path("logout/", logout_view, name='logout'),
    path('profile/<int:user_id>', profile, name='profile'),
    path('edit/<int:user_id>', edit, name='edit'),
    path('update_profile/<int:user_id>', update_profile, name='update_profile'),

] 

bbubbu/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    
    return render(request, "index.html")

def main(request):
    return render(request, 'main.html')

bbubbu/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>뿌뿌</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
       <!-- Favicon-->
  <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
  <!-- =======================================================
  * Template Name: MyResume - v4.5.0
  * Template URL: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    {% include 'shared/navbar.html' %}

    {% block content %}

    <!-- 여기 내용 들어감 -->

    {% endblock %}

    {% comment %} {% include 'shared/footer.html' %} {% endcomment %}

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
  <script src="{% static 'vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/typed.js/typed.min.js' %}"></script>
  <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

bbubbu/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section id="hero" class="d-flex flex-column justify-content-center">
  <style>
    .btn{
      padding: none;
      border-style: solid black;
      
    }
  </style>
    <div class="container" data-aos="zoom-in" data-aos-delay="100">

      <h1 ><p class="head-title" >동국대학생 교류 서비스 <span class="typed" data-typed-items=", 뿌뿌 "></span></p></h1>
      
      <br>
      <p><h7 style="line-height: 3rem;">여러 대학교에는 현재 뻔문화라는 것이 존재합니다.<br>
          뻔 문화란 뒷자리 학번이 같은 뻔선배 뻔후배 간의 관계에서 비롯한 문화를 의미합니다.<br>
          학번을 통해 선후배 관계를 맺는 문화인 뻔문화를 동국대학교에서도 누려보세요.
        </h7></p>
        
      {% if user.is_authenticated %}
      <button type="button"  class="btn" > <a href="{%url 'main' %}" > 입장하기</a></button> 
      <button type="button"  class="btn"> <a href="{%url 'user:logout' %}" > 로그아웃</a></button>
      {% else %}
        
      <button type="button"  class="btn"> <a href="{%url 'user:login' %}" >로그인</a></button>
      <button type="button"  class="btn"> <a href="{%url 'user:signup' %}" >회원가입</a></button>

      {% endif %}
    </div>
</section><!-- End Hero -->

{%endblock%}

bbubbu/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



  <section id="services" class="services">
      <br><br><br>
    <div class="container" data-aos="fade-up">
      <div class="section-title">
        <h2>HELLO !</h2>
        <br>
        <p>"뻔라인"을 누르시면 뻔라인을 조회하실 수 있습니다. <br>"긱라인"을 누르시면 긱라인을 조회하실 수 있습니다.<br>라인이 없으시다면 '입양'을 추천드릴게요! 🐰</p>
      </div>
      <br><br><br>
      <div class='row' style="justify-content: space-around;">
        <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-md-0" data-aos="zoom-in" data-aos-delay="200">
          <div class="icon-box iconbox-orange">
            <div class="icon"><i class="bx bx-file"></i></div>
            <h4><a href="{% url 'matching:match_view' request.user.id %}">뻔라인</a></h4>
            <p>같은 학과, 학번 뒤 세자리가 같은 한 학번 선배를 자동 팔로잉 해드립니다 :)</p>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-lg-0" data-aos="zoom-in" data-aos-delay="300">
          <div class="icon-box iconbox-yellow">
            <div class="icon"><i class="bx bx-tachometer"></i></div>
            <h4><a href="{%url 'dormline:view_random' request.user.id %}">긱라인</a></h4>
            <p>같은 층의 학생을 랜덤으로 다섯명 리스트업합니다 :)</p>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 d-flex align-items-stretch mt-4 mt-lg-0" data-aos="zoom-in" data-aos-delay="100">
          <div class="icon-box iconbox-orange">
            <div class="icon"><i class="bx bx-world"></i></div>
            <h4><a href="{% url 'adopt:adopt_main'%}">입양하기</a></h4>
            <p>뻔라인과 긱라인이 없다면 입양을 클릭해주세요 :)</p>
          </div>
        </div>
    </div>
    </div>
  </section>
<br><br><br>
<section id="testimonials" class="testimonials section-bg">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <h2>MY FOLLOWING <br> MY FOllOWER<br></h2>
        <br>
      </div>

      <div class="testimonials-slider swiper" data-aos="fade-up" data-aos-delay="100">
        <div class="swiper-wrapper">
   
          <div class="swiper-slide">
            <div class="testimonial-item">
              <img src="{% static 'assets/img/testimonials/testimonials-1.jpg' %}" class="testimonial-img" alt="">
              <h3>나의 뻔선</h3>
              <br>
              {% if request.user.s_followings.all %}
              {% for a in request.user.s_followings.all %}
              <h4>{{a.name}}</h4>
              <h4>{{a.department}}</h4>
              {% endfor %}
              {% else %}
              <h4>아직 없습니다 :(</h4>
              {% endif %}
            </div>
          </div><!-- End testimonial item -->
          <div class="swiper-slide">
            <div class="testimonial-item">
              <img src="{% static 'assets/img/testimonials/testimonials-2.jpg' %}" class="testimonial-img" alt="">
              <h3>나의 뻔후</h3>
              <br>
              {% if request.user.s_followers.all %}
              {% for a in request.user.s_followers.all %}
              <h4>{{a.name}}</h4>
              <h4>{{a.department}}</h4>
              {% endfor %}
              {% else %}
              <h4>아직 없습니다 :(</h4>
              {% endif %}
            </div>
          </div><!-- End testimonial item -->

          <div class="swiper-slide">
            <div class="testimonial-item">
              <img src="{% static 'assets/img/testimonials/testimonials-3.jpg' %}" class="testimonial-img" alt="">
              <h3>긱라인 FOLLOWING</h3>
              <br>
              {% if request.user.d_followings.all %}
              {% for a in request.user.d_followings.all %}
              <h4>{{a.name}}</h4>
              <h4>{{a.department}}</h4>
              {% endfor %}
              {% else %}
              <h4>아직 없습니다 :(</h4>
              {% endif %}
            </div>
          </div><!-- End testimonial item -->

          <div class="swiper-slide">
            <div class="testimonial-item">
              <img src="{% static 'assets/img/testimonials/testimonials-4.jpg '%}" class="testimonial-img" alt="">
              <h3>긱라인 FOLLOWER</h3>
              <br>
              {% if request.user.d_followers.all %}
              {% for a in request.user.d_followers.all %}
              <h4>{{a.name}}</h4>
              <h4>{{a.department}}</h4>
              {% endfor %}
              {% else %}
              <h4>아직 없습니다 :(</h4>
              {% endif %}
            </div>
          </div><!-- End testimonial item -->

        </div>
        <div class="swiper-pagination"></div>
      </div>

    </div>
  </section>
{%endblock%}