adopt/urls.py
from django.urls import path
from .views import *

app_name="adopt"

urlpatterns = [
    path('',adopt_main,name="adopt_main"),
    path('adopt_try/<int:id>', adopt_try,name="adopt_try"),
    path('adopting/<int:id>',adopting,name="adopting"),
] 

bbubbu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name="index"),
    path('main/',main, name='main'),
    # path('accounts/',include("allauth.urls")),
    path('stories/',include('stories.urls')),
    path('user/',include('user.urls')),
    path('matching/',include('matching.urls')),
    path('adopt/',include('adopt.urls')),
    path('conversation/',include('conversation.urls')),
    path('dormline/',include('dormline.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

matching/urls.py
from django.urls import path
from .views import *

app_name="matching"

urlpatterns = [
    path("match_upline/<int:id>",match_view, name="match_view" ),
    # path("school_line/<int:id>",shcool_line, name="school_line" ),

] 

stories/urls.py
from django.urls import path
from .views import *

app_name="stories"

urlpatterns = [
    path('list/',list,name="list"),
    path('new_story/',new_story,name="new_story"),
    path('my_story/',my_story,name="my_story"),
    path('create/',create,name="create"),
    path('detail<int:id>',detail,name="detail"),
    path('edit_story/<int:id>',edit_story,name="edit_story"),
    path('update/<int:id>',update,name="update"),
    path('delete/<int:id>',delete,name="delete"),

] 

user/urls.py
from django.urls import path
from .views import *

app_name="user"
urlpatterns = [
    path('login',login_view, name='login'),
    path('signup/',signup_view,name='signup'),
    path("main/", main, name='main'),
    path("logout/", logout_view, name='logout'),
    path('profile/<int:user_id>', profile, name='profile'),
    path('edit/<int:user_id>', edit, name='edit'),
    path('update_profile/<int:user_id>', update_profile, name='update_profile'),

] 

stories/models.py
from django.db import models
from django.conf import settings
# from django.contrib.auth.models import User 이거 못쓰던데 물어보기

User = settings.AUTH_USER_MODEL
# Create your models here.

class Story(models.Model):
    id = models.AutoField(primary_key=True)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to="story/",null=True, blank=True)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now=False)
    updated_at = models.DateTimeField(auto_now=True)

stories/views.py
from django.shortcuts import get_object_or_404, render,redirect
from .models import Story
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.

def list(request):
    stories = Story.objects.all()
    return render(request,"list.html",{"stories":stories})


def new_story(request):
    return render(request,"new_story.html")

def my_story(request):
    stories = Story.objects.filter(writer=request.user)
    return render(request,"my_story.html",{"stories":stories})

def create(request):
    new_story=Story()
    new_story.title = request.POST["title"]
    new_story.writer = request.user
    new_story.image = request.FILES.get("image")
    new_story.body = request.POST["body"]
    new_story.created_at = timezone.now()
    new_story.updated_at = timezone.now()
    new_story.save()
    return redirect("stories:detail",new_story.id)


def detail(request,id):
    story = get_object_or_404(Story,pk=id)

    return render(request, "detail.html",{"story":story})


def edit_story(request,id):
    story = Story.objects.get(id=id)
    return render(request,"edit_story.html",{"story":story})


def update(request, id):
    update_story=Story.objects.get(id=id)
    update_story.title = request.POST["title"]
    update_story.writer = request.user
    update_story.image = request.FILES.get("image")
    update_story.body = request.POST["body"]
    update_story.updated_at = timezone.now()
    update_story.save()
    return redirect("stories:detail",update_story.id)


def delete(request,id):
    delete_story = Story.objects.get(id=id)
    delete_story.delete()
    return redirect("stories:list")

stories/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- ======= Portfolio Details Section ======= -->
<section id="portfolio-details" class="portfolio-details">
    <div class="container">

        <div class="row gy-4">

            <div class="col-lg-8">
                <div class="portfolio-details-slider swiper">
                    <div class="swiper-wrapper align-items-center">

                        {% comment %} <div class="swiper-slide">
                            <img src="{% static 'img/portfolio/portfolio-details-1.jpg' %}" alt="">
                        </div> {% endcomment %}


                        {% comment %} <div class="swiper-slide">
                            <img src="{% static 'img/portfolio/portfolio-details-3.jpg' %}" alt="">
                        </div> {% endcomment %}
                        {%if story.image%}
                        <div class="swiper-slide">
                            <img src="{{story.image.url}}" alt="img">
                        </div>
                        {%else%}

                        <div class="swiper-slide">
                            <img src="{% static 'img/portfolio/portfolio-details-2.jpg' %}" alt="">
                        </div>
                        {%endif%}
                    </div>
                    <div class="swiper-pagination"></div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="portfolio-info">
                    <h3>{{story.title}}</h3>
                    <ul>
                        <li><strong>Writer</strong> : {{story.writer}}</li>
                        <li><strong>Body</strong> : {{story.body}}</li>
                        <li><strong>생성시간</strong> : {{story.created_at}}</li>
                        <li><strong>수정시간</strong> : {{story.updated_at}}</li>
                    </ul>
                    <br>
        
                    <ul>
                    {% if story.writer == request.user %}
                        <a class="btn btn-dark" href="{% url 'stories:edit_story' story.id %}">수정하기</a>
                        <a class="btn btn-dark" href="{% url 'stories:delete' story.id %}">삭제하기</a>
                    {% endif%}
                    </ul>
                </div>
            </div>

        </div>

    </div>
</section><!-- End Portfolio Details Section -->

{%endblock%}

stories/templates/edit_story.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
.confirmBtn {
  margin-top: 10px;
  width: 100px;
  color: white;
  background-color: #ff8668;
  padding: 6px;
  border: none;
  border-radius: 8px;
  margin-bottom: 30px;
  font-weight: bold;
}
</style>
    <section id="portfolio-details" class="portfolio-details">
    <div class="container">
        <form action="{%url 'stories:update' story.id %}" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            <p>제목 : <input value="{{story.title}}" type="text" name="title" required></p>
            <p>사진 : <input value="{{story.image}}" type="file" name="image">{{story.image}}</p>
            <p>내용 : <textarea style="width: 100%;" type="text" name="body" id="" cols="50" rows="10"
                    required>{{story.body}}</textarea></p>
            <button class="confirmBtn" type="submit">제출</button>
        </form>
        </div>
    </section>
{%endblock%}

stories/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>

</style>

<section id="portfolio-details"  class="portfolio-details">
    
    <header class="py-5">
        <div class="container px-lg-5">
            <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
                <div class="m-4 m-lg-5">
                    <h1 class="display-5 fw-bold">후기 포스팅</h1><br><br>
                    <p class="fs-4" >뻔라인, 긱라인, 입양을 사용한 유저들의 후기입니다!<br> 여러분의 이야기도 들려주세요!</p><br>
                    
                {% if user.is_authenticated %}
                    <a class="btn btn-primary btn-lg" href="{% url 'stories:new_story' %}" style="background-color:#fe7f5d; border-color:white;">후기 작성하기</a>
                    <a class="btn btn-primary btn-lg" href="{% url 'stories:my_story' %}" style="background-color:#fe7f5d; border-color:white;">내 후기 모아보기</a>
                {%else%}
                    <a class="btn btn-primary btn-lg" href="{% url 'user:login' %}" style="background-color:#fe7f5d; border-color:white;">후기 작성하기</a>
                    <a class="btn btn-primary btn-lg" href="{% url 'user:login' %}" style="background-color:#fe7f5d; border-color:white;">내 후기 모아보기</a>

                {%endif%}

                    
                </div>
            </div>
        </div>
    </header>
    
    <div class="container" style="margin-top : 5%;  ">


        {%for story in stories%}
           
            
                <div class="portfolio-info" >
                    <h3> <a style="color:black;" href="{% url 'stories:detail' story.id %}">{{story.title}}</a></h3>
                    <ul>
                        <li><strong>Writer</strong> : {{story.writer}}</li>
                        <li><strong>Body</strong> : {{story.body|truncatechars:7}}</li>
                        <li><strong>생성시간</strong> : {{story.created_at}}</li>
                        <li><strong>수정시간</strong> : {{story.updated_at}}</li>
                    </ul>
                </div>
           
           
        {%endfor%}

        

    </div>
    
</section>
{%endblock%}

stories/templates/my_story.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>

</style>

<section id="portfolio-details"  class="portfolio-details">
{% if stories %}
          
    <header class="py-5">
        <div class="container px-lg-5">
            <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
                <div class="m-4 m-lg-5">
                    <h1 class="display-5 fw-bold">내가 작성한 후기</h1><br><br>
                    <p class="fs-4" >내가 그동안 작성한 후기입니다!</p>
                    <a class="btn btn-primary btn-lg" href="{% url 'stories:new_story' %}" style="background-color:#fe7f5d; border-color:white;">후기 작성하기</a>
                    <a class="btn btn-primary btn-lg" href="{% url 'stories:list' %}" style="background-color:#fe7f5d; border-color:white;">모든 후기 보러가기</a>
                </div>
            </div>
        </div>
    </header>
    
    <div class="container" style="margin-top : 5%; ">

    
        {%for story in stories%}
           
            <div class="col-lg-12">
                <div class="portfolio-info">
                    <h3> <a style="color:black;" href="{% url 'stories:detail' story.id %}">{{story.title}}</a></h3>
                    <ul>
                        <li><strong>Writer</strong> : {{story.writer}}</li>
                        <li><strong>Body</strong> : {{story.body|truncatechars:7}}</li>
                        <li><strong>생성시간</strong> : {{story.created_at}}</li>
                        <li><strong>수정시간</strong> : {{story.updated_at}}</li>
                    </ul>
                </div>
            </div>
           
        {%endfor%}
    
{% else %}
    <header class="py-5">
        <div class="container px-lg-5">
            <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
                <div class="m-4 m-lg-5">
                    <h1 class="display-5 fw-bold">내가 작성한 후기</h1><br><br>
                    <p class="fs-4" >내가 작성한 후기가 없습니다!</p><br>
                    <a class="btn btn-primary btn-lg" href="{% url 'stories:new_story' %}" style="background-color:#fe7f5d; border-color:white;">후기 작성하기</a>
                    <a class="btn btn-primary btn-lg" href="{% url 'stories:list' %}" style="background-color:#fe7f5d; border-color:white;">모든 후기 보러가기</a>
                </div>
            </div>
        </div>
    </header>

        

    </div>
{% endif %}
</section>
{%endblock%}

stories/templates/new_story.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
.confirmBtn {
  margin-top: 10px;
  width: 100px;
  color: white;
  background-color: #ff8668;
  padding: 6px;
  border: none;
  border-radius: 8px;
  margin-bottom: 30px;
  font-weight: bold;
}
</style>
    <section id="portfolio-details" class="portfolio-details">
        <div class="container">
        <form action="{%url 'stories:create'%}" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            <p>제목 : <input type="text" name="title" required></p>
            <p>사진 : <input type="file" name="image"></p>
            <p>내용 : <textarea style="width: 100%;" type="text" name="body" id="" cols="50" rows="10"
                    required></textarea></p>
            <button class="confirmBtn" type="submit">제출</button>
        </form>
        </div>
    </section>
{%endblock%}

stories/templates/storylist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section id="portfolio-details" class="portfolio-details">
    <div class="container">
        <h3><a style="color:black;" href="{% url 'stories:new_story' %}">나의 뻔모임은?</a></h3><br>
        <h3><a style="color:black;" href="{% url 'adopt:adopt_main'%}">입양?</a></h3><br>
        <h3><a style="color:black;" href="{% url 'dormline:dorm_main' %}">긱라인?</a></h3><br>

        <h3><a style="color:black;" href="{% url 'stories:new_story' %}">후기 글쓰기</a></h3><br>
        {%for story in stories%}
           
            <div class="col-lg-12">
                <div class="portfolio-info">
                    <h3> <a style="color:black;" href="{% url 'stories:detail' story.id %}">{{story.title}}</a></h3>
                    <ul>
                        <li><strong>Writer</strong> : {{story.writer}}</li>
                        <li><strong>Body</strong> : {{story.body|truncatechars:7}}</li>
                        <li><strong>생성시간</strong> : {{story.created_at}}</li>
                        <li><strong>수정시간</strong> : {{story.updated_at}}</li>
                    </ul>
                </div>
            </div>
           
        {%endfor%}

        
        {% if not request.user.s_followings %}
        <h3><a style="color:black;" href="{% url 'matching:match_view' request.user.id %}">뻔라인 조회</a></h3><br>
        {% endif %}
        <a href="{% url 'dormline:dorm_main' %}">긱라인 조회</a>
    </div>
</section>
{%endblock%}