bbubbu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name="index"),
    path('main/',main, name='main'),
    # path('accounts/',include("allauth.urls")),
    path('stories/',include('stories.urls')),
    path('user/',include('user.urls')),
    path('matching/',include('matching.urls')),
    path('adopt/',include('adopt.urls')),
    path('conversation/',include('conversation.urls')),
    path('dormline/',include('dormline.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *

app_name="user"
urlpatterns = [
    path('login',login_view, name='login'),
    path('signup/',signup_view,name='signup'),
    path("main/", main, name='main'),
    path("logout/", logout_view, name='logout'),
    path('profile/<int:user_id>', profile, name='profile'),
    path('edit/<int:user_id>', edit, name='edit'),
    path('update_profile/<int:user_id>', update_profile, name='update_profile'),

] 

user/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User,BaseUserManager,AbstractBaseUser,PermissionsMixin
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, username, nickname, password, name, email, department, school_id, is_dorm, dorm_id):
        user=self.model(
            username=username,
            nickname=nickname,
            name=name,
            email=email,
            department=department,
            school_id=school_id,
            is_dorm=is_dorm,
            dorm_id=dorm_id,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self, nickname, username, password):
        user=self.create_user(
            username=username,
            nickname=nickname,
            password=password,
            name='',
            email='',
            department='',
            school_id=0,
            is_dorm=False,
            dorm_id=0,
        )
        user.set_password(password)
        user.is_admin=True
        user.is_superuser=True
        user.is_staff=True
        user.save(using=self._db)
        return user
    
class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=50, unique=True, default='')
    #아이디
    nickname = models.CharField(max_length=100, unique=True, default='')
    #닉네임
    name=models.CharField(max_length=30, default='')
    #이름
    email = models.EmailField(max_length=30,default='')
    #이메일
    CHOICE_DEPART=(
        ('AI융합학부','AI융합학부'),
        ('가정교육과','가정교육과'),
        ('건설환경공학과','건설환경공학과'),
        ('건축공학부','건축공학부'),
        ('경영정보학과','경영정보학과'),
        ('경영학과','경영학과'),
        ('경제학과','경제학과'),
        ('경찰행정학부','경찰행정학부'),
        ('광고홍보학과','광고홍보학과'),
        ('교육학과','교육학과'),
        ('국어교육과','국어교육과'),
        ('국어국문학전공','국어국문학전공'),
        ('국제통상학과','국제통상학과'),
        ('글로벌무역학과','글로벌무역학과'),
        ('기계로봇에너지공학과','기계로봇에너지공학과'),
        ('멀티미디어공학과','멀티미디어공학과'),
        ('문예창작학전공','문예창작학전공'),
        ('물리학전공','물리학전공'),
        ('뮤지컬전공','뮤지컬전공'),
        ('미디어커뮤니케이션학전공','미디어커뮤니케이션학전공'),
        ('바이오환경과학과','바이오환경과학과'),
        ('반도체과학전공','반도체과학전공'),
        ('법학과','법학과'),
        ('북한학전공','북한학전공'),
        ('불교미술전공','불교미술전공'),
        ('불교학부','불교학부'),
        ('사학과','사학과'),
        ('사회복지상담학과','사회복지상담학과'),
        ('사회복지학과','사회복지학과'),
        ('사회학전공','사회학전공'),
        ('산업시스템공학과','산업시스템공학과'),
        ('생명과학과','생명과학과'),
        ('서양화전공','서양화전공'),
        ('수학과','수학과'),
        ('수학교육과','수학교육과'),
        ('스포츠문화학과','스포츠문화학과'),
        ('식품산업관리학과','식품산업관리학과'),
        ('식품생명공학과','식품생명공학과'),
        ('약학과','약학과'),
        ('역사교육과','역사교육과'),
        ('연극전공','연극전공'),
        ('영어문학전공','영어문학전공'),
        ('영어통번역학전공','영어통번역학전공'),
        ('영화영상학과','영화영상학과'),
        ('윤리문화학전공','윤리문화학전공'),
        ('융합보안학과','융합보안학과'),
        ('융합에너지신소재공학과','융합에너지신소재공학과'),
        ('의생명공학과','의생명공학과'),
        ('일본학과','일본학과'),
        ('전자전기공학부','전자전기공학부'),
        ('정보통신공학전공','정보통신공학전공'),
        ('정치외교학전공','정치외교학전공'),
        ('조소전공','조소전공'),
        ('중어중문학과','중어중문학과'),
        ('지리교육과','지리교육과'),
        ('철학과','철학과'),
        ('체육교육과','체육교육과'),
        ('컴퓨터공학전공','컴퓨터공학전공'),
        ('통계학과','통계학과'),
        ('한국화전공','한국화전공'),
        ('행정학전공','행정학전공'),
        ('화공생물공학과','화공생물공학과'),
        ('화학과','화학과'),
        ('회계학과','회계학과')
    )
    department=models.CharField(max_length=50, choices=CHOICE_DEPART,default='')
    #학과
    school_id = models.CharField(max_length=30,default='')
    #학번
    is_dorm=models.CharField(max_length=10,default='')
    #기숙사생 여부 체크 
    dorm_id=models.CharField(max_length=30, default='')
    #기숙사 번호
    # image = models.ImageField(upload_to="user/",blank=True, null=True)
    d_followings=models.ManyToManyField("self",related_name='d_followers',symmetrical=False)
    s_followings=models.ManyToManyField("self",related_name='s_followers',symmetrical=False)
    
    objects=UserManager()
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD='username'
    REQUIRED_FIELDS=['nickname']

    def __str__(self):
        return self.username

user/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import auth
from .models import User
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, "index.html")

def test(request):
    return render(request, 'test.html')


#회원가입
def signup_view(request):
    res_data = {}
    if request.method=='GET':
        return render(request,'signup.html')
    elif request.method =='POST':
        username=request.POST['username']
        password=request.POST['password1']
        re_password=request.POST['password2']
        nickname=request.POST['nickname']
        name=request.POST['name']
        email=request.POST['email']
        department=request.POST['department']
        school_id=request.POST['school_id']
        is_dorm=request.POST['is_dorm']
        dorm_id=request.POST['dorm_id']

        res_data={}
        #unique값인 username과 nickname 예외처리를 위한
        all=User.objects.all()
        username_lst=[x.username for x in all]
        nick_lst=[x.nickname for x in all]
        if not (username and password and nickname and name and email and department and school_id and is_dorm):
            res_data['error']= "모든 값을 입력해야합니다."
        elif password != re_password:
            res_data['error']= "비밀번호가 다릅니다."
        elif email.split('@')[1] != 'dongguk.edu':
            res_data['error']= "@dongguk.edu로 가입해야합니다."
        elif username in username_lst:
            res_data['error']="이미 있는 아이디입니다."
        elif nickname in nick_lst:
            res_data['error']="이미 있는 닉네임입니다."
        else:
            user=User.objects.create_user(
                username=username,
                password=password,
                nickname=nickname,
                name=name,
                email=email,
                department=department,
                school_id=school_id,
                is_dorm=is_dorm,
                dorm_id=dorm_id,)
            user.save()
            auth.login(request,user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('index')
        return render(request, 'signup.html',res_data)
        

#로그인
def login_view(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        User = auth.authenticate(username = username, password = password)
        
        if User is not None:
            auth.login(request, User)
            return redirect('index')
            
            #여기 main.html 연결시켜줘야함.

    return render(request, 'login.html')

#로그아웃
@login_required
def logout_view(request):
    auth.logout(request)
    return redirect('/')

def main(request):
    return render(request, "main.html")


#내 정보 보기
def profile(request,user_id):
    profile=User.objects.get(id=user_id)
    return render(request, 'profile.html',{'profile':profile})

def edit(request,user_id):
    profile=User.objects.get(id=user_id)
    return render(request,'edit.html',{'profile':profile})

def update_profile(request,user_id):
    profile=User.objects.get(id=user_id)
    
    if request.method =='POST':
        # print(request.FILES.get('photo'))
        # if request.FILES.get('photo'):
        #     profile.image=request.FILES['photo']
        profile.username=request.POST['username']
        profile.password1=request.POST['password1']
        profile.password2=request.POST['password2']
        profile.nickname=request.POST['nickname']
        profile.name=request.POST['name']
        profile.department=request.POST['department']
        profile.school_id=request.POST['school_id']
        profile.is_dorm=request.POST['is_dorm']
        if(profile.is_dorm=='no'):
            profile.dorm_id=''
        else:
            profile.dorm_id=request.POST['dorm_id']
        profile.save()
    return redirect('user:profile',profile.id)
        
      

user/templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <style>
        /* signup_container*/

        .signup_container {
            display: flex;
            flex-direction: column;
            margin: 0 auto;
            margin-top: 40px;
            width: 80%;
            text-align: center;
            overflow: auto;
        }

        .signup_title {
            font-weight: 100;
            margin-top: 30px;
            font-size: 30px;
            margin-bottom: 50px;
        }

        .signup_input_container {
            display: block;
            margin: 0 auto;
            height: 3%;
            margin-bottom: 20px;
        }

        .signup_input_title {
            border:none;
            width: 200px;
            text-align: left;
            
            font-size: 12px;
            margin-bottom: 10px;
        }

        .signup {
            width: 200px;
            height: 40px;
            background-color: white;
            border: 1px solid lightgray;
            border-radius: 8px;
            padding: 10px;
            margin-bottom: 5px;
            font-size: 10px;
        }

        #hobbyBtn {
            margin-top: 10px;
            width: 100px;
            color: white;
            background-color: #4ccd97;
            padding: 6px;
            border: none;
            border-radius: 8px;
        }

        #confirmBtn {
            margin-top: 10px;
            width:200px;
            color: white;
            background-color: #ff8668;
            padding: 6px;
            border: none;
            border-radius: 8px;
            margin-bottom: 30px;
            font-weight: bold;
        }
    </style>

<div class="row mt-5">
    <div class="col-12">
        {{ error }}
    </div>
</div>
<section>
    <div class="container" data-aos="zoom-in" data-aos-delay="100">
        <div class="signup_container">
            <form action="{%url 'user:update_profile' profile.id%}" method="POST">
                {%csrf_token%}
                {% comment %} <div class="signup_input_container">
                    <div class="signup_input_title">사진</div>
                    <input name="photo" type="file" accept="image/*">
                </div> {% endcomment %}
                <div class="signup_input_container">
                    <input class="signup_input_title" disabled value="아이디"><br>

                    <input type="text" class="signup" name="username" value="{{profile.username}}">
                </div>
                <div class="signup_input_container">
                <input class="signup_input_title" disabled value="비밀번호"><br>

                    <input required type="password" class="signup" name="password1" placeholder="비밀번호 입력해주세요">
                </div>
                <div class="signup_input_container">
                    <input class="signup_input_title" disabled value="비밀번호 확인"><br>

                    <input required type="password" class="signup" name="password2" placeholder="비밀번호 다시 입력해주세요">
                </div>
                <div class="signup_input_container">
                    <input class="signup_input_title" disabled value="닉네임"><br>

                    <input type="text" class="signup" name="nickname" value="{{profile.nickname}}">
                </div>
                <div class="signup_input_container">
                    <input class="signup_input_title" disabled value="이름"><br>

                    <input type="text" class="signup" name="name" value="{{profile.name}}">
                </div>
                <div class="signup_input_container">
                    <input class="signup_input_title" disabled value="학과"><br>

                    <select style='font-size:12px;' name="department">
                        <option value="AI융합학부">AI융합학부</option>
                        <option value="가정교육과">가정교육과</option>
                        <option value="건설환경공학과">건설환경공학과</option>
                        <option value="건축공학전공">건축공학전공</option>
                        <option value="건축학전공">건축학전공</option>
                        <option value="경영정보학과">경영정보학과</option>
                        <option value="경영학과">경영학과</option>
                        <option value="경제학과">경제학과</option>
                        <option value="경찰행정학부">경찰행정학부</option>
                        <option value="광고홍보학과">광고홍보학과</option>
                        <option value="교육학과">교육학과</option>
                        <option value="국어교육과">국어교육과</option>
                        <option value="국어국문학전공">국어국문학전공</option>
                        <option value="국제통상학과">국제통상학과</option>
                        <option value="글로벌무역학과">글로벌무역학과</option>
                        <option value="기계로봇에너지공학과">기계로봇에너지공학과</option>
                        <option value="멀티미디어공학과">멀티미디어공학과</option>
                        <option value="문예창작학전공">문예창작학전공</option>
                        <option value="물리학전공">물리학전공</option>
                        <option value="뮤지컬전공">뮤지컬전공</option>
                        <option value="미디어커뮤니케이션학전공">미디어커뮤니케이션학전공</option>
                        <option value="바이오환경과학과">바이오환경과학과</option>
                        <option value="반도체과학전공">반도체과학전공</option>
                        <option value="법학과">법학과</option>
                        <option value="북한학전공">북한학전공</option>
                        <option value="불교미술전공">불교미술전공</option>
                        <option value="불교학부">불교학부</option>
                        <option value="사학과">사학과</option>
                        <option value="사회복지상담학과">사회복지상담학과</option>
                        <option value="사회복지학과">사회복지학과</option>
                        <option value="사회학전공">사회학전공</option>
                        <option value="산업시스템공학과">산업시스템공학과</option>
                        <option value="생명과학과">생명과학과</option>
                        <option value="서양화전공">서양화전공</option>
                        <option value="수학과">수학과</option>
                        <option value="수학교육과">수학교육과</option>
                        <option value="스포츠문화학과">스포츠문화학과</option>
                        <option value="식품산업관리학과">식품산업관리학과</option>
                        <option value="식품생명공학과">식품생명공학과</option>
                        <option value="약학과">약학과</option>
                        <option value="역사교육과">역사교육과</option>
                        <option value="연극전공">연극전공</option>
                        <option value="영어문학전공">영어문학전공</option>
                        <option value="영어통번역학전공">영어통번역학전공</option>
                        <option value="영화영상학과">영화영상학과</option>
                        <option value="윤리문화학전공">윤리문화학전공</option>
                        <option value="융합보안학과">융합보안학과</option>
                        <option value="융합에너지신소재공학과">융합에너지신소재공학과</option>
                        <option value="의생명공학과">의생명공학과</option>
                        <option value="일본학과">일본학과</option>
                        <option value="전자전기공학부">전자전기공학부</option>
                        <option value="정보통신공학전공">정보통신공학전공</option>
                        <option value="정치외교학전공">정치외교학전공</option>
                        <option value="조소전공">조소전공</option>
                        <option value="중어중문학과">중어중문학과</option>
                        <option value="지리교육과">지리교육과</option>
                        <option value="철학과">철학과</option>
                        <option value="체육교육과">체육교육과</option>
                        <option value="컴퓨터공학전공">컴퓨터공학전공</option>
                        <option value="통계학과">통계학과</option>
                        <option value="한국화전공">한국화전공</option>
                        <option value="행정학전공">행정학전공</option>
                        <option value="화공생물공학과">화공생물공학과</option>
                        <option value="화학과">화학과</option>
                        <option value="회계학과">회계학과</option>
                    </select>
                </div>
                <div class="signup_input_container">
                    <input class="signup_input_title" disabled value="학번"><br>
                    <input type="text" class="signup" name="school_id" value="{{profile.school_id}}">
                </div>
                <div class="signup_input_container">
                    <input class="signup_input_title" disabled value="기숙사생 여부"><br>

                    <div>
                        <span id="hobbyRadio" style="font-size: 13px;"><input type="radio" name="is_dorm"
                                value="yes">기숙사생</span>
                        <span id="hobbyRadio" style="font-size: 13px;"><input checked type="radio" name="is_dorm"
                                value="no">아님</span>
                    </div>
                </div>
                <div class="signup_input_container">
                    <input class="signup_input_title" disabled value="기숙사 번호"><br>

                    <input type="text" class="signup" default='' name="dorm_id"
                        {% if 'no' in profile.is_dorm %}placeholder="기숙사번호 (기숙사생 아닐시 입력하지 않음) "
                        {%else%}value="{{profile.dorm_id}}" {%endif%}>
                </div>
                <button id="confirmBtn" type="submit">완료</button>
            </form>
        </div>
    </div>
</section>

{%endblock%}

user/templates/error.html
~<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    동국대 웹메일로 로그인 해주세요
    <a href="{%url 'index' %}" }>signup</a>
    
</body>
</html>

user/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


  <style>
    /* signup_container*/

    .signup_container {
      display: flex;
      flex-direction: column;
      margin: 0 auto;
      margin-top: 40px;
      width: 80%;
      text-align: center;
    }

    .signup_title {
      font-weight: 100;
      margin-top: 30px;
      font-size: 30px;
      margin-bottom: 50px;
    }

    .signup_input_container {
      display: block;
      margin: 0 auto;
 

      margin-bottom: 20px;
    }

    .signup_input_title {
      border:none;
      width: 200px;
      text-align: left;
      
      font-size: 12px;
      margin-bottom: 10px;
  }

    .signup {
      width: 200px;
      height: 40px;
      background-color: white;
      border: 1px solid lightgray;
      border-radius: 8px;
      padding: 10px;
      margin-bottom: 5px;
      font-size: 10px;
    }

    #hobbyBtn {
      margin-top: 10px;
      width: 100px;
      color: white;
      background-color: #4ccd97;
      padding: 6px;
      border: none;
      border-radius: 8px;
    }

    #confirmBtn {
      margin-top: 10px;
      width: 150px;
      color: white;
      background-color: #ff8668;
      padding: 6px;
      border: none;
      border-radius: 8px;
      margin-bottom: 30px;
      font-weight: bold;
    }

    .sign {
      margin-top: 10px;
      width: 200px;
      color: white;
      background-color: #ff8668;
      padding: 6px;
      border: none;
      border-radius: 8px;
      margin-bottom: 30px;
      font-weight: bold;
    }
  </style>
<section>
 <div class="container" data-aos="zoom-in" data-aos-delay="100">
    <div class="signup_container">
      <form action="{%url 'user:login' %}" method="POST">
        {%csrf_token%}
        <div class="signup_title">로그인</div>

        <div class="signup_input_container">
          <input style="background:transparent;" class="signup_input_title" disabled value="아이디"><br>

          <input type="text" class="signup" name="username" placeholder="아이디">
        </div>
        <br>
        <div class="signup_input_container">
          <input style="background:transparent;" class="signup_input_title" disabled value="비밀번호"><br>

          <input type="password" class="signup" name="password" placeholder="비밀번호">

        </div>
        <br>
        <button id="confirmBtn" type="submit">완료</button>
        <a class="sign" href="{%url 'user:signup' %}">회원가입</a>
      </form>
    </div>
  </div>
</section>
{%endblock%}

user/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
body {
    background: #eee
}

.card {
    border: none;
    position: relative;
    overflow: hidden;
    border-radius: 8px;
    cursor: pointer;
    border-radius: 10px;
}

.card:before {
    content: "";
    position: absolute;
    left: 0;
    top: 0;
    width: 4px;
    height: 100%;
    background-color: #ffd5d9;
    transform: scaleY(1);
    transition: all 0.5s;
    transform-origin: bottom
}

.card:after {
    content: "";
    position: absolute;
    left: 0;
    top: 0;
    width: 4px;
    height: 100%;
    background-color: #fe7f5d;
    transform: scaleY(0);
    transition: all 0.5s;
    transform-origin: bottom
}

.card:hover::after {
    transform: scaleY(1)
}

.fonts {
    font-size: 11px
}

.social-list {
    display: flex;
    list-style: none;
    justify-content: center;
    padding: 0
}

.social-list li {
    padding: 10px;
    color: #fe7f5d;
    font-size: 19px
}

.buttons button:nth-child(1) {
    border: 1px solid #fe7f5d !important;
    color: #fff;
    height: 40px
}

.buttons button:nth-child(1):hover {
    border: 1px solid #fe7f5d !important;
    color: #fff;
    height: 40px;
    background-color: #fe7f5d;
    
}

.buttons button:nth-child(2) {
    border: 1px solid #8E24AA !important;
    background-color: #8E24AA;
    color: #fff;
    height: 40px
}

.bg-secondary p-1 px-4 rounded text-white{
    background-color: #fe7f5d;
}

.modify-info {
    color:#fe7f5d;
}

.modify-info:hover {
    color:#fff;
}

</style>

<section id="portfolio-d">
<div class="container mt-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-7">
            <div class="card p-3 py-4">
                <div class="text-center">
                    {%if profile.image%}
                     <img src="{{profile.image.url}}" width="100" class="rounded-circle"> 
                     {%endif%}
                    </div>
                
                <div class="text-center mt-3"> <span class="bg-secondary p-1 px-4 rounded text-white">회원정보</span>
                    <h5 class="mt-2 mb-0"><br>
                        <div class="signup_input_container">
                            <div class="signup_input_title">아이디 : </div>
                            <input readonly type="text" class="signup" name="username" value="{{profile.username}}">
                        </div><br>
                        
                        <div class="signup_input_container">
                            <div class="signup_input_title">닉네임 : </div><input readonly type="text" class="signup" name="nickname" value="{{profile.nickname}}">
                        </div><br>
                        <div class="signup_input_container">
                            <div class="signup_input_title">이름 : </div>
                            <input readonly type="text" class="signup" name="name" value=" {{profile.name}}">
                        </div><br>
                        <div class="signup_input_container">
                            <div class="signup_input_title">학과 : </div>
                            <input readonly type="text" class="signup" name="department" value="{{profile.department}}">
                        </div><br>
                        <div class="signup_input_container">
                            <div class="signup_input_title">학번 : </div>
                            <input readonly type="text" class="signup" name="school_id" value="{{profile.school_id}}">
                        </div><br>
                        
                        {% if 'no' in profile.is_dorm %}
                        <div class="signup_input_container">
                            <div class="signup_input_title">기숙사생 여부 : </div>
                            <div>
                                <input readonly type="text" name="is_dorm" value="{{profile.is_dorm}}">
                            </div>
                        </div><br>
                        {%else%}
                        <div class="signup_input_container">
                            <div class="signup_input_title">기숙사생 여부 : </div>
                            <div>
                                <input readonly type="text" name="is_dorm" value="{{profile.is_dorm}}">
                            </div>
                        </div><br>
                        <div class="signup_input_container">
                            <div class="signup_input_title">기숙사 번호 : </div>
                            <input readonly type="text" class="signup" default='' name="dorm_id" value="{{profile.dorm_id}}">
                        </div><br>
                        
                        </div>
                        {%endif%}
                    <div class="buttons"> <button class="btn btn-outline-primary px-4"><a class="modify-info" href="{%url 'user:edit' profile.id %}">개인정보 수정하기</a></button></div>
                    
                
                </div>
            </div>
        </div>
    </div>
</div>
</section>
{%endblock%}