adopt/urls.py
from django.urls import path
from .views import *

app_name="adopt"

urlpatterns = [
    path('',adopt_main,name="adopt_main"),
    path('adopt_try/<int:id>', adopt_try,name="adopt_try"),
    path('adopting/<int:id>',adopting,name="adopting"),
] 

bbubbu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name="index"),
    path('main/',main, name='main'),
    # path('accounts/',include("allauth.urls")),
    path('stories/',include('stories.urls')),
    path('user/',include('user.urls')),
    path('matching/',include('matching.urls')),
    path('adopt/',include('adopt.urls')),
    path('conversation/',include('conversation.urls')),
    path('dormline/',include('dormline.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

conversation/urls.py
from django.urls import path
from .views import *

app_name="conversation"

urlpatterns = [
    path('',talk_page,name="talk_page"),
    path('create_talk/',create_talk,name="create_talk"),
    path('edit_talk/<int:talk_id>',edit_talk,name="edit_talk"),
    path('update_talk/<int:talk_id>',update_talk,name="update_talk"),
    path('delete_talk/<int:talk_id>',delete_talk,name="delete_talk"),

] 

dormline/urls.py
from django.urls import path
from .views import *

app_name='dormline'
urlpatterns = [
    path('view_random/<str:id>', view_random, name='view_random'),
    path('follow/<str:id>',follow, name='follow'),
] 

stories/urls.py
from django.urls import path
from .views import *

app_name="stories"

urlpatterns = [
    path('list/',list,name="list"),
    path('new_story/',new_story,name="new_story"),
    path('my_story/',my_story,name="my_story"),
    path('create/',create,name="create"),
    path('detail<int:id>',detail,name="detail"),
    path('edit_story/<int:id>',edit_story,name="edit_story"),
    path('update/<int:id>',update,name="update"),
    path('delete/<int:id>',delete,name="delete"),

] 

user/urls.py
from django.urls import path
from .views import *

app_name="user"
urlpatterns = [
    path('login',login_view, name='login'),
    path('signup/',signup_view,name='signup'),
    path("main/", main, name='main'),
    path("logout/", logout_view, name='logout'),
    path('profile/<int:user_id>', profile, name='profile'),
    path('edit/<int:user_id>', edit, name='edit'),
    path('update_profile/<int:user_id>', update_profile, name='update_profile'),

] 

bbubbu/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    
    return render(request, "index.html")

def main(request):
    return render(request, 'main.html')

bbubbu/templates/shared/footer.html
  {% load static %}
  <!-- ======= Footer ======= -->
<div id="preloader"></div>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<footer id="footer">
    <div class="container">
      <h5>Donnguk</h5>
      <p>BBuBBu</p>
      
      <div class="copyright">
        &copy; Copyright <strong><span>MyResume</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: [license-url] -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->


  

bbubbu/templates/shared/navbar.html
{% load static %}
{% comment %} <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container px-lg-5">
      <a class="navbar-brand" href="#!">BBUBBU</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a></li>
          </ul>
      </div>
  </div>
</nav> {% endcomment %}
 <!-- ======= Mobile nav toggle button ======= -->
  <!-- <button type="button" class="mobile-nav-toggle d-xl-none"><i class="bi bi-list mobile-nav-toggle"></i></button> -->
  <i class="bi bi-list mobile-nav-toggle d-xl-none"></i>
  <!-- ======= Header ======= -->
  <header id="header" class="d-flex flex-column justify-content-center">

    <nav id="navbar" class="navbar nav-menu">
      <ul>
        <li><a href="{% url 'index' %}" class="nav-link scrollto active"><i class="bx bx-home"></i> <span>Home</span></a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'user:profile' request.user.id %}" class="nav-link scrollto"><i class="bx bx-user"></i> <span>Profile</span></a></li>
        <li><a href="{% url 'conversation:talk_page'%}" class="nav-link scrollto"><i class="bx bx-file-blank"></i> <span>Talk</span></a></li>
        <li><a href="{% url 'adopt:adopt_main'%}" class="nav-link scrollto"><i class="bx bx-book-content"></i> <span>입양하기</span></a></li>
        <li><a href="{% url 'dormline:view_random' request.user.id %}" class="nav-link scrollto"><i class="bx bx-server"></i> <span>긱라인</span></a></li>
        {% endif %}
        <li><a href="{%url 'stories:list' %}" class="nav-link scrollto"><i class="bx bx-envelope"></i> <span>후기 포스팅</span></a></li>
      </ul>
    </nav><!-- .nav-menu -->

  </header><!-- End Header -->